"""add skill column

Revision ID: 50ca1a19a4f2
Revises: bc08cfa65ea6
Create Date: 2024-11-07 05:09:22.074533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ca1a19a4f2'
down_revision: Union[str, None] = 'bc08cfa65ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('skill', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'skill')
    # ### end Alembic commands ###
